spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_jwt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
